nvt_NH Class Reference
Uses Nose-Hover integration method to thermostat a system (constant T rather than E)
#include <nvt.h>
Public Member Functions
nvt_NH (const float Q)
void step (systemDefinition &sys)
void setTimestep (const float dt)
Set the integrator timestep.
void calcForce (systemDefinition &sys)
Calculate the forces on each atom.
Protected Attributes
cellList_cpu cl_
Cell or neighbor list.
std::vector< float3 > lastAccelerations_
Acceleration of particles on previous timestep (useful for NVE integrator)
float dt_
Timestep size.
int start_
Flag for whether this object has been initialized or not.
Detailed Description
Uses Nose-Hover integration method to thermostat a system (constant T rather than E)
NVT integration with Nose-Hoover thermostat.
Date
11/18/13
Definition at line 13 of file nvt.h.
Constructor & Destructor Documentation
nvt_NH::nvt_NH (const float Q)
Do NVT integration with Nose-Hoover thermostat.
Date
11/18/13
Initialize integrator
Parameters
in Q Thermal mass for thermostat
Definition at line 20 of file nvt.cpp.
References integrator::start_.
                             {
    Q_ = Q;
    gamma_ = 0.0;
    start_ = 1;
}
Member Function Documentation
void integrator::calcForce (systemDefinition & sys) [inherited]
Calculate the forces on each atom.
Integration
Date
11/19/13
Calculate the pairwise forces in a system. This also calculates the potential energy of a system. The kinetic energy is calculated during the verlet integration.
Parameters
in,out sys System definition
Definition at line 22 of file integrator.cpp.
References systemDefinition::atoms, systemDefinition::box(), cellList_cpu::checkUpdate(), integrator::cl_, cellList_cpu::head(), cellList_cpu::list(), systemDefinition::mass(), cellList_cpu::nCells, cellList_cpu::neighbors(), systemDefinition::numAtoms(), systemDefinition::potential, systemDefinition::potentialArgs(), systemDefinition::rcut(), and systemDefinition::setPotE().
Referenced by nve::step(), and step().
                                                 {
    // For cache coeherency allocate new space for calculations
    float3 empty;
    empty.x = 0; empty.y = 0; empty.z = 0;
    std::vector <float3> acc (sys.numAtoms(), empty);
    const float rc = sys.rcut();
    // every time, check if the cell list needs to be updated first
    cl_.checkUpdate(sys);
    float Up = 0.0;
    const float3 box = sys.box();
    const float invMass = 1.0/sys.mass();
    
    // traverse cell list and calculate total system potential energy
    std::vector <float> args = sys.potentialArgs();
    #pragma omp parallel for reduction(+:Up) schedule(dynamic, 1)
    for (unsigned int cellID = 0; cellID < cl_.nCells.x*cl_.nCells
      .y*cl_.nCells.z; ++cellID) {
        int atom1 = cl_.head(cellID);
        while (atom1 >= 0) {
            std::vector < int > neighbors = cl_.neighbors(cellID);
            for (int index = 0; index < neighbors.size(); ++index) {
                const int cellID2 = neighbors[index];
                int atom2 = cl_.head(cellID2);
                while (atom2 >= 0) {
                    if (atom1 > atom2) {
                        float3 pf;
                        Up += sys.potential (&sys.atoms[atom1].
      pos, &sys.atoms[atom2].pos, &pf, &box, &args[0], &rc);
                        acc[atom1].x -= pf.x*invMass;
                        acc[atom1].y -= pf.y*invMass;
                        acc[atom1].z -= pf.z*invMass;
                        acc[atom2].x += pf.x*invMass;
                        acc[atom2].y += pf.y*invMass;
                        acc[atom2].z += pf.z*invMass;
                    }
                    atom2 = cl_.list(atom2);
                }
            }
            atom1 = cl_.list(atom1);
        }
    }
    
    // save acceleration in array of atoms in system
    #pragma omp parallel for
    for (int i = 0; i < sys.numAtoms(); ++i) {
        sys.atoms[i].acc.x = -acc[i].x;
        sys.atoms[i].acc.y = -acc[i].y;
        sys.atoms[i].acc.z = -acc[i].z;
    }
    
    // set Up
    sys.setPotE(Up);
}
void nvt_NH::step (systemDefinition & sys) [virtual]
Integrate a single timestep forward using Velocity-Verlet integration scheme. This is NOT identical since some intermediate bookkeeping needs to be handled for thermostat. Creates a cell list the first time it is called.
Parameters
in,out sys System definition
Implements integrator.
Definition at line 32 of file nvt.cpp.
References systemDefinition::atoms, systemDefinition::box(), integrator::calcForce(), integrator::cl_, integrator::dt_, systemDefinition::instantT(), systemDefinition::mass(), systemDefinition::numAtoms(), systemDefinition::rcut(), systemDefinition::rskin(), systemDefinition::setKinE(), integrator::start_, systemDefinition::targetT(), and systemDefinition::updateInstantTemp().
                                        {
    int chunk = OMP_CHUNK;
    if (start_) {
        try {
            cellList_cpu tmpCL (sys.box(), sys.rcut(), sys.
      rskin());
            cl_ = tmpCL;
        } catch (std::exception &e) {
            std::cerr << e.what() << std:: endl;
            throw customException("Failed to integrate on first
       step");
        }
        gamma_ = 0.0;
        for (unsigned int i = 0; i < sys.numAtoms(); ++i) {
            gamma_ += (sys.atoms[i].vel.x*sys.atoms[i].vel.x)+(sys.
      atoms[i].vel.y*sys.atoms[i].vel.y)+(sys.atoms[i].vel.z*sys.atoms
      [i].vel.z);
        }
        gamma_ -= (3.0*(sys.numAtoms()-1.0))*sys.instantT();
        gamma_ /= Q_;
        // get initial temperature
        calcForce(sys);
        float tmp=0.0, Uk = 0.0;
        #pragma omp parallel for reduction(+:Uk)
        for (unsigned int i = 0; i < sys.numAtoms(); ++i) {
            Uk += (sys.atoms[i].vel.x*sys.atoms[i].vel.x)+(sys.atoms
      [i].vel.y*sys.atoms[i].vel.y)+(sys.atoms[i].vel.z*sys.atoms[i].
      vel.z);
        }
        Uk *= sys.mass();
        tmp = Uk;
        Uk *= 0.5;
        tmp /= (3.0*(sys.numAtoms()-1.0));
        sys.updateInstantTemp(tmp);
        sys.setKinE(Uk);
        start_ = 0;
        gammadot_ = 0.0;
        gammadd_ = 0.0;
    }
    
    tau2_ = Q_/ ((3.0*(sys.numAtoms()-1.0))*sys.targetT());
    gammadd_ = 1/tau2_*(sys.instantT()/sys.targetT()-1);
    
    // (1) update thermostat velocity and thermostat position
    // velocity half-step
    gammadot_ += dt_*0.5*gammadd_;
    
    // position step
    gamma_ += gammadot_*dt_;
    
    // (2) evolve particle velocities
    #pragma omp parallel shared(sys)
    {
        #pragma omp for schedule(dynamic,OMP_CHUNK)
        for (unsigned int i = 0; i < sys.numAtoms(); ++i) {
            sys.atoms[i].vel.x = sys.atoms[i].vel.x*exp(-gammadot_*
      dt_*0.5) + 0.5*dt_*(sys.atoms[i].acc.x);
            sys.atoms[i].vel.y = sys.atoms[i].vel.y*exp(-gammadot_*
      dt_*0.5) + 0.5*dt_*(sys.atoms[i].acc.y);
            sys.atoms[i].vel.z = sys.atoms[i].vel.z*exp(-gammadot_*
      dt_*0.5) + 0.5*dt_*(sys.atoms[i].acc.z);
        }
        // (3) evolve particle positions
        #pragma omp for schedule(dynamic,OMP_CHUNK)
        for (unsigned int i = 0; i < sys.numAtoms(); ++i) {
            sys.atoms[i].pos.x += sys.atoms[i].vel.x*dt_;
            sys.atoms[i].pos.y += sys.atoms[i].vel.y*dt_;
            sys.atoms[i].pos.z += sys.atoms[i].vel.z*dt_;
        }
    }
    
    // (4) calc force
    calcForce(sys);
    
    // (5) evolve particle velocities
    #pragma omp parallel shared(sys)
    {
    #pragma omp for schedule(dynamic,OMP_CHUNK)
    for (unsigned int i = 0; i < sys.numAtoms(); ++i) {
        sys.atoms[i].vel.x = (sys.atoms[i].vel.x+sys.atoms[i].
      acc.x*dt_*0.5)*exp(-gammadot_*dt_*0.5);
        sys.atoms[i].vel.y = (sys.atoms[i].vel.y+sys.atoms[i].
      acc.y*dt_*0.5)*exp(-gammadot_*dt_*0.5);
        sys.atoms[i].vel.z = (sys.atoms[i].vel.z+sys.atoms[i].
      acc.z*dt_*0.5)*exp(-gammadot_*dt_*0.5);
        }
    }
    float Uk = 0.0;
    float tmp = 0.0;
    #pragma omp parallel for reduction(+:Uk)
    // get temperature and kinetic energy
    for (unsigned int i = 0; i < sys.numAtoms(); ++i) {
        Uk += (sys.atoms[i].vel.x*sys.atoms[i].vel.x)+(sys.atoms
      [i].vel.y*sys.atoms[i].vel.y)+(sys.atoms[i].vel.z*sys.atoms[i].
      vel.z);
    }
    
    Uk *= sys.mass();
    tmp = Uk;
    Uk *= 0.5;
    tmp /= (3.0*(sys.numAtoms()-1.0));
    sys.updateInstantTemp(tmp);
    sys.setKinE(Uk);
    // (6) update thermostat velocity
    gammadd_ = 1/tau2_*(sys.instantT()/sys.targetT()-1);
    gammadot_ += dt_*0.5*gammadd_;
}
The documentation for this class was generated from the following files:
/Users/nathanmahynski/Desktop/CBEMDGPU/nvt.h
/Users/nathanmahynski/Desktop/CBEMDGPU/nvt.cpp